import jsPDF from 'jspdf';
import { format } from 'date-fns';

type CurrencyCode = 'USD' | 'NGN' | 'GBP' | 'EUR';

const CURRENCY_SYMBOLS: Record<CurrencyCode, string> = {
  USD: '$',
  NGN: '₦',
  GBP: '£',
  EUR: '€',
};

const formatCurrency = (amount: number, currency: CurrencyCode = 'NGN'): string => {
  const symbol = CURRENCY_SYMBOLS[currency] || '₦';
  return `${symbol}${amount.toLocaleString('en-NG', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
};

interface SaleRecord {
  id: string;
  sale_date: string;
  quantity: number;
  unit_price: number;
  total_price: number;
  customer_name: string | null;
  medications: { name: string; category: string } | null;
}

interface MedicationRecord {
  id: string;
  name: string;
  category: string;
  batch_number: string;
  current_stock: number;
  reorder_level: number;
  unit_price: number;
  selling_price: number | null;
  expiry_date: string;
}

export const exportSalesToPDF = (
  sales: SaleRecord[],
  dateRange: { from?: Date; to?: Date },
  pharmacyName: string,
  currency: CurrencyCode = 'NGN'
): jsPDF => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageWidth = 210;
  const margin = 15;
  let y = 20;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Sales Report', pageWidth / 2, y, { align: 'center' });
  y += 8;
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(pharmacyName, pageWidth / 2, y, { align: 'center' });
  y += 6;
  
  const dateText = dateRange.from && dateRange.to 
    ? `${format(dateRange.from, 'MMM d, yyyy')} - ${format(dateRange.to, 'MMM d, yyyy')}`
    : `Generated: ${format(new Date(), 'MMM d, yyyy')}`;
  doc.setFontSize(10);
  doc.text(dateText, pageWidth / 2, y, { align: 'center' });
  y += 12;

  // Summary
  const totalRevenue = sales.reduce((sum, s) => sum + Number(s.total_price), 0);
  const totalItems = sales.reduce((sum, s) => sum + s.quantity, 0);
  
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y, pageWidth - margin * 2, 20, 'F');
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total Revenue: ${formatCurrency(totalRevenue, currency)}`, margin + 5, y + 8);
  doc.text(`Total Orders: ${sales.length}`, margin + 80, y + 8);
  doc.text(`Items Sold: ${totalItems}`, margin + 140, y + 8);
  y += 28;

  // Table Header
  const colWidths = [25, 55, 25, 25, 30, 30];
  const headers = ['Date', 'Medication', 'Qty', 'Unit Price', 'Total', 'Customer'];
  
  doc.setFillColor(50, 50, 50);
  doc.rect(margin, y, pageWidth - margin * 2, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  
  let x = margin + 2;
  headers.forEach((header, i) => {
    doc.text(header, x, y + 5.5);
    x += colWidths[i];
  });
  y += 10;
  doc.setTextColor(0, 0, 0);

  // Table Rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  
  sales.forEach((sale, index) => {
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
    
    if (index % 2 === 0) {
      doc.setFillColor(250, 250, 250);
      doc.rect(margin, y - 3, pageWidth - margin * 2, 7, 'F');
    }
    
    x = margin + 2;
    doc.text(format(new Date(sale.sale_date), 'MM/dd'), x, y);
    x += colWidths[0];
    
    const medName = sale.medications?.name || 'Unknown';
    doc.text(medName.length > 28 ? medName.substring(0, 28) + '...' : medName, x, y);
    x += colWidths[1];
    
    doc.text(sale.quantity.toString(), x, y);
    x += colWidths[2];
    
    doc.text(formatCurrency(sale.unit_price, currency), x, y);
    x += colWidths[3];
    
    doc.text(formatCurrency(sale.total_price, currency), x, y);
    x += colWidths[4];
    
    const customer = sale.customer_name || 'Walk-in';
    doc.text(customer.length > 15 ? customer.substring(0, 15) + '...' : customer, x, y);
    
    y += 7;
  });

  // Footer
  y = 285;
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by PharmaTrack on ${format(new Date(), 'MMM d, yyyy h:mm a')}`, pageWidth / 2, y, { align: 'center' });

  return doc;
};

export const exportSalesToExcel = (
  sales: SaleRecord[],
  currency: CurrencyCode = 'NGN'
): string => {
  const headers = ['Date', 'Time', 'Transaction ID', 'Medication', 'Category', 'Quantity', 'Unit Price', 'Total', 'Customer'];
  
  const rows = sales.map(sale => [
    format(new Date(sale.sale_date), 'yyyy-MM-dd'),
    format(new Date(sale.sale_date), 'HH:mm:ss'),
    sale.id.slice(0, 8),
    sale.medications?.name || 'Unknown',
    sale.medications?.category || 'Unknown',
    sale.quantity.toString(),
    sale.unit_price.toString(),
    sale.total_price.toString(),
    sale.customer_name || 'Walk-in',
  ]);

  const csv = [headers, ...rows].map(row => 
    row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',')
  ).join('\n');

  return csv;
};

export const exportInventoryToPDF = (
  medications: MedicationRecord[],
  pharmacyName: string,
  currency: CurrencyCode = 'NGN'
): jsPDF => {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'mm', format: 'a4' });
  const pageWidth = 297;
  const margin = 10;
  let y = 15;

  // Header
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Inventory Report', pageWidth / 2, y, { align: 'center' });
  y += 7;
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(pharmacyName, pageWidth / 2, y, { align: 'center' });
  y += 5;
  
  doc.setFontSize(10);
  doc.text(`Generated: ${format(new Date(), 'MMM d, yyyy h:mm a')}`, pageWidth / 2, y, { align: 'center' });
  y += 10;

  // Summary Stats
  const totalValue = medications.reduce((sum, m) => sum + (m.current_stock * m.unit_price), 0);
  const lowStock = medications.filter(m => m.current_stock <= m.reorder_level).length;
  const expiredCount = medications.filter(m => new Date(m.expiry_date) <= new Date()).length;
  
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y, pageWidth - margin * 2, 15, 'F');
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(`Total SKUs: ${medications.length}`, margin + 5, y + 7);
  doc.text(`Inventory Value: ${formatCurrency(totalValue, currency)}`, margin + 55, y + 7);
  doc.text(`Low Stock Items: ${lowStock}`, margin + 130, y + 7);
  doc.text(`Expired Items: ${expiredCount}`, margin + 190, y + 7);
  y += 22;

  // Table Header
  const colWidths = [50, 28, 28, 22, 22, 28, 28, 28, 30, 30];
  const headers = ['Medication', 'Category', 'Batch', 'Stock', 'Reorder', 'Cost Price', 'Sell Price', 'Value', 'Expiry', 'Status'];
  
  doc.setFillColor(50, 50, 50);
  doc.rect(margin, y, pageWidth - margin * 2, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  
  let x = margin + 2;
  headers.forEach((header, i) => {
    doc.text(header, x, y + 5.5);
    x += colWidths[i];
  });
  y += 10;
  doc.setTextColor(0, 0, 0);

  // Table Rows
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  
  medications.forEach((med, index) => {
    if (y > 195) {
      doc.addPage();
      y = 15;
    }
    
    const isLowStock = med.current_stock <= med.reorder_level;
    const isExpired = new Date(med.expiry_date) <= new Date();
    
    if (isExpired) {
      doc.setFillColor(255, 230, 230);
    } else if (isLowStock) {
      doc.setFillColor(255, 250, 230);
    } else if (index % 2 === 0) {
      doc.setFillColor(250, 250, 250);
    } else {
      doc.setFillColor(255, 255, 255);
    }
    doc.rect(margin, y - 3, pageWidth - margin * 2, 6, 'F');
    
    x = margin + 2;
    const name = med.name.length > 25 ? med.name.substring(0, 25) + '...' : med.name;
    doc.text(name, x, y);
    x += colWidths[0];
    
    const cat = med.category.length > 14 ? med.category.substring(0, 14) + '...' : med.category;
    doc.text(cat, x, y);
    x += colWidths[1];
    
    doc.text(med.batch_number.slice(0, 12), x, y);
    x += colWidths[2];
    
    doc.text(med.current_stock.toString(), x, y);
    x += colWidths[3];
    
    doc.text(med.reorder_level.toString(), x, y);
    x += colWidths[4];
    
    doc.text(formatCurrency(med.unit_price, currency), x, y);
    x += colWidths[5];
    
    doc.text(formatCurrency(med.selling_price || med.unit_price, currency), x, y);
    x += colWidths[6];
    
    const value = med.current_stock * med.unit_price;
    doc.text(formatCurrency(value, currency), x, y);
    x += colWidths[7];
    
    doc.text(format(new Date(med.expiry_date), 'MM/dd/yy'), x, y);
    x += colWidths[8];
    
    let status = 'OK';
    if (isExpired) status = 'EXPIRED';
    else if (isLowStock) status = 'LOW STOCK';
    doc.text(status, x, y);
    
    y += 6;
  });

  // Footer
  y = 200;
  doc.setFontSize(7);
  doc.setTextColor(128, 128, 128);
  doc.text(`Generated by PharmaTrack`, pageWidth / 2, y, { align: 'center' });

  return doc;
};

export const exportInventoryToExcel = (
  medications: MedicationRecord[],
  currency: CurrencyCode = 'NGN'
): string => {
  const headers = ['Name', 'Category', 'Batch Number', 'Current Stock', 'Reorder Level', 'Cost Price', 'Selling Price', 'Stock Value', 'Expiry Date', 'Status'];
  
  const rows = medications.map(med => {
    const isLowStock = med.current_stock <= med.reorder_level;
    const isExpired = new Date(med.expiry_date) <= new Date();
    let status = 'OK';
    if (isExpired) status = 'EXPIRED';
    else if (isLowStock) status = 'LOW STOCK';
    
    return [
      med.name,
      med.category,
      med.batch_number,
      med.current_stock.toString(),
      med.reorder_level.toString(),
      med.unit_price.toString(),
      (med.selling_price || med.unit_price).toString(),
      (med.current_stock * med.unit_price).toString(),
      format(new Date(med.expiry_date), 'yyyy-MM-dd'),
      status,
    ];
  });

  const csv = [headers, ...rows].map(row => 
    row.map(cell => `"${String(cell).replace(/"/g, '""')}"`).join(',')
  ).join('\n');

  return csv;
};

export const downloadFile = (content: string | Blob, filename: string, type: string = 'text/csv') => {
  const blob = content instanceof Blob ? content : new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
